name: flutter_barcode_scanner_example
description: Demonstrates how to use the flutter_barcode_scanner plugin for Android and iOS.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_plugin_android_lifecycle: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_barcode_scanner:
    path: ../

  pedantic: ^1.9.2

flutter:
  uses-material-design: true
